/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    'works-groups': WorksGroup;
    works: Work;
    'team-members': TeamMember;
    'press-items': PressItem;
    users: User;
    media: Media;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    'works-groups': WorksGroupsSelect<false> | WorksGroupsSelect<true>;
    works: WorksSelect<false> | WorksSelect<true>;
    'team-members': TeamMembersSelect<false> | TeamMembersSelect<true>;
    'press-items': PressItemsSelect<false> | PressItemsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | 'en' | 'en'[];
  globals: {
    'site-config': SiteConfig;
    navigation: Navigation;
  };
  globalsSelect: {
    'site-config': SiteConfigSelect<false> | SiteConfigSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
  };
  locale: 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  hero: {
    type: 'cinematic' | 'page' | 'minimal';
    headline?: string | null;
    subtitle?: string | null;
    /**
     * Small uppercase label above the headline (e.g. "OUR WORK", "ABOUT US")
     */
    label?: string | null;
    media?: (number | null) | Media;
    /**
     * CSS object-position value (e.g. "center top", "50% 30%")
     */
    imagePosition?: string | null;
  };
  layout: (
    | ContentBlock
    | MediaBlockType
    | CTABlock
    | TwoColumnLayoutBlock
    | WorksGridBlock
    | WorksScrollBlock
    | FeaturedWorkBlock
    | TeamShowcaseBlock
    | PressListBlock
    | ContactInfoBlock
    | ContactFormBlock
    | LegalSectionsBlock
  )[];
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
    /**
     * Comma-separated keywords for <meta name="keywords">
     */
    keywords?: string | null;
    /**
     * Override canonical URL (leave empty for auto-generated)
     */
    canonicalUrl?: string | null;
    /**
     * JSON-LD @type for structured data
     */
    jsonLdType?: ('WebPage' | 'ItemPage' | 'AboutPage' | 'ContactPage' | 'CollectionPage') | null;
    /**
     * Optional custom JSON-LD (injected verbatim). For advanced use only.
     */
    jsonLdCustom?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  publishedAt?: string | null;
  /**
   * URL slug ("home" is reserved for the homepage)
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    poster?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock".
 */
export interface ContentBlock {
  columns?:
    | {
        size?: ('full' | 'half' | 'oneThird' | 'twoThirds') | null;
        richText: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
      }[]
    | null;
  /**
   * Background tone for this section
   */
  sectionTone?: ('default' | 'deep' | 'charcoal' | 'slate' | 'warm' | 'cool' | 'ember' | 'dusk') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlockType".
 */
export interface MediaBlockType {
  media: number | Media;
  caption?: string | null;
  size?: ('full' | 'contained') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CTABlock".
 */
export interface CTABlock {
  richText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  links?:
    | {
        label: string;
        url: string;
        isExternal?: boolean | null;
        appearance?: ('default' | 'outline' | 'gold') | null;
        id?: string | null;
      }[]
    | null;
  sectionTone?: ('default' | 'deep' | 'charcoal' | 'warm') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TwoColumnLayoutBlock".
 */
export interface TwoColumnLayoutBlock {
  leftColumn?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Image for the left column (optional if using rich text)
   */
  leftMedia?: (number | null) | Media;
  rightColumn?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Image for the right column (optional if using rich text)
   */
  rightMedia?: (number | null) | Media;
  reverseOnMobile?: boolean | null;
  sectionTone?: ('default' | 'deep' | 'charcoal' | 'slate' | 'warm' | 'cool') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'twoColumnLayout';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WorksGridBlock".
 */
export interface WorksGridBlock {
  title?: string | null;
  /**
   * Choose how to populate this grid
   */
  sourceType?: ('all' | 'pick' | 'group') | null;
  /**
   * Pick and reorder individual works for this grid
   */
  selectedWorks?: (number | Work)[] | null;
  /**
   * Pick a reusable works group
   */
  worksGroup?: (number | null) | WorksGroup;
  /**
   * Show category/tag filter tabs above the grid
   */
  showFilters?: boolean | null;
  /**
   * Show subcategory tabs (for development page)
   */
  showSubcategoryTabs?: boolean | null;
  /**
   * Pre-filter works by category
   */
  category?: ('film' | 'series' | 'unscripted') | null;
  /**
   * Maximum number of works to display
   */
  limit?: number | null;
  sectionTone?: ('default' | 'charcoal' | 'deep') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'worksGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "works".
 */
export interface Work {
  id: number;
  title: string;
  slug: string;
  year: number;
  poster?: (number | null) | Media;
  tags?: ('Drama' | 'Thriller' | 'True Crime' | 'Unscripted')[] | null;
  description?: string | null;
  /**
   * YouTube or Vimeo embed URL
   */
  videoUrl?: string | null;
  category?: ('film' | 'series' | 'unscripted') | null;
  subcategory?: string | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    keywords?: string | null;
  };
  /**
   * Lower = first
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Curated lists of works for use in page blocks (grids, scroll strips, etc.)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "works-groups".
 */
export interface WorksGroup {
  id: number;
  /**
   * Internal label (e.g. "Home Featured", "Development Projects")
   */
  name: string;
  slug: string;
  /**
   * Pick and reorder works. Drag to set display order.
   */
  items: (number | Work)[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WorksScrollBlock".
 */
export interface WorksScrollBlock {
  title?: string | null;
  /**
   * Choose how to populate this scroll strip
   */
  sourceType?: ('all' | 'pick' | 'group' | 'manual') | null;
  /**
   * Pick and reorder individual works
   */
  selectedWorks?: (number | Work)[] | null;
  /**
   * Pick a reusable works group
   */
  worksGroup?: (number | null) | WorksGroup;
  /**
   * Manual items with per-item size/label control
   */
  items?:
    | {
        /**
         * Select a work, or use the manual fields below
         */
        work?: (number | null) | Work;
        /**
         * Override image (or use for non-work items like BTS photos)
         */
        media?: (number | null) | Media;
        /**
         * Override label (e.g. "Lifetime", "On set")
         */
        label?: string | null;
        size?: ('large' | 'medium' | 'small') | null;
        id?: string | null;
      }[]
    | null;
  ctaLabel?: string | null;
  ctaUrl?: string | null;
  sectionTone?: ('default' | 'warm' | 'charcoal') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'worksScroll';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeaturedWorkBlock".
 */
export interface FeaturedWorkBlock {
  /**
   * Select a work to feature
   */
  work?: (number | null) | Work;
  /**
   * Override the poster image (optional)
   */
  overridePoster?: (number | null) | Media;
  /**
   * Featured quote or tagline
   */
  quote?: string | null;
  /**
   * Quote attribution (e.g. "Deadline Hollywood")
   */
  attribution?: string | null;
  /**
   * Link to external article or trailer
   */
  externalUrl?: string | null;
  layout?: ('split' | 'overlay') | null;
  sectionTone?: ('default' | 'deep' | 'charcoal' | 'warm' | 'ember' | 'dusk') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'featuredWork';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TeamShowcaseBlock".
 */
export interface TeamShowcaseBlock {
  title?: string | null;
  introText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  showBios?: boolean | null;
  showPhotos?: boolean | null;
  sectionTone?: ('default' | 'charcoal' | 'deep' | 'warm') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'teamShowcase';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PressListBlock".
 */
export interface PressListBlock {
  title?: string | null;
  /**
   * Maximum number of press items. Use a small number for teasers.
   */
  limit?: number | null;
  /**
   * Show a "View All" link to the press page
   */
  showViewAll?: boolean | null;
  viewAllUrl?: string | null;
  sectionTone?: ('default' | 'charcoal' | 'deep' | 'slate' | 'warm') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'pressList';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactInfoBlock".
 */
export interface ContactInfoBlock {
  title?: string | null;
  showEmail?: boolean | null;
  showPhone?: boolean | null;
  showAddress?: boolean | null;
  showSocials?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'contactInfo';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactFormBlock".
 */
export interface ContactFormBlock {
  title?: string | null;
  subtitle?: string | null;
  /**
   * Email address for mailto form. Defaults to site contact email if empty.
   */
  recipientEmail?: string | null;
  nameLabel?: string | null;
  emailLabel?: string | null;
  messageLabel?: string | null;
  submitLabel?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'contactForm';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LegalSectionsBlock".
 */
export interface LegalSectionsBlock {
  sections?:
    | {
        title: string;
        content: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'legalSections';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members".
 */
export interface TeamMember {
  id: number;
  name: string;
  role: string;
  bio: string;
  photo?: (number | null) | Media;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "press-items".
 */
export interface PressItem {
  id: number;
  title: string;
  source: string;
  date: string;
  url: string;
  description?: string | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'works-groups';
        value: number | WorksGroup;
      } | null)
    | ({
        relationTo: 'works';
        value: number | Work;
      } | null)
    | ({
        relationTo: 'team-members';
        value: number | TeamMember;
      } | null)
    | ({
        relationTo: 'press-items';
        value: number | PressItem;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  hero?:
    | T
    | {
        type?: T;
        headline?: T;
        subtitle?: T;
        label?: T;
        media?: T;
        imagePosition?: T;
      };
  layout?:
    | T
    | {
        content?: T | ContentBlockSelect<T>;
        mediaBlock?: T | MediaBlockTypeSelect<T>;
        cta?: T | CTABlockSelect<T>;
        twoColumnLayout?: T | TwoColumnLayoutBlockSelect<T>;
        worksGrid?: T | WorksGridBlockSelect<T>;
        worksScroll?: T | WorksScrollBlockSelect<T>;
        featuredWork?: T | FeaturedWorkBlockSelect<T>;
        teamShowcase?: T | TeamShowcaseBlockSelect<T>;
        pressList?: T | PressListBlockSelect<T>;
        contactInfo?: T | ContactInfoBlockSelect<T>;
        contactForm?: T | ContactFormBlockSelect<T>;
        legalSections?: T | LegalSectionsBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
        keywords?: T;
        canonicalUrl?: T;
        jsonLdType?: T;
        jsonLdCustom?: T;
      };
  publishedAt?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock_select".
 */
export interface ContentBlockSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        size?: T;
        richText?: T;
        id?: T;
      };
  sectionTone?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlockType_select".
 */
export interface MediaBlockTypeSelect<T extends boolean = true> {
  media?: T;
  caption?: T;
  size?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CTABlock_select".
 */
export interface CTABlockSelect<T extends boolean = true> {
  richText?: T;
  links?:
    | T
    | {
        label?: T;
        url?: T;
        isExternal?: T;
        appearance?: T;
        id?: T;
      };
  sectionTone?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TwoColumnLayoutBlock_select".
 */
export interface TwoColumnLayoutBlockSelect<T extends boolean = true> {
  leftColumn?: T;
  leftMedia?: T;
  rightColumn?: T;
  rightMedia?: T;
  reverseOnMobile?: T;
  sectionTone?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WorksGridBlock_select".
 */
export interface WorksGridBlockSelect<T extends boolean = true> {
  title?: T;
  sourceType?: T;
  selectedWorks?: T;
  worksGroup?: T;
  showFilters?: T;
  showSubcategoryTabs?: T;
  category?: T;
  limit?: T;
  sectionTone?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WorksScrollBlock_select".
 */
export interface WorksScrollBlockSelect<T extends boolean = true> {
  title?: T;
  sourceType?: T;
  selectedWorks?: T;
  worksGroup?: T;
  items?:
    | T
    | {
        work?: T;
        media?: T;
        label?: T;
        size?: T;
        id?: T;
      };
  ctaLabel?: T;
  ctaUrl?: T;
  sectionTone?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeaturedWorkBlock_select".
 */
export interface FeaturedWorkBlockSelect<T extends boolean = true> {
  work?: T;
  overridePoster?: T;
  quote?: T;
  attribution?: T;
  externalUrl?: T;
  layout?: T;
  sectionTone?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TeamShowcaseBlock_select".
 */
export interface TeamShowcaseBlockSelect<T extends boolean = true> {
  title?: T;
  introText?: T;
  showBios?: T;
  showPhotos?: T;
  sectionTone?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PressListBlock_select".
 */
export interface PressListBlockSelect<T extends boolean = true> {
  title?: T;
  limit?: T;
  showViewAll?: T;
  viewAllUrl?: T;
  sectionTone?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactInfoBlock_select".
 */
export interface ContactInfoBlockSelect<T extends boolean = true> {
  title?: T;
  showEmail?: T;
  showPhone?: T;
  showAddress?: T;
  showSocials?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactFormBlock_select".
 */
export interface ContactFormBlockSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  recipientEmail?: T;
  nameLabel?: T;
  emailLabel?: T;
  messageLabel?: T;
  submitLabel?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LegalSectionsBlock_select".
 */
export interface LegalSectionsBlockSelect<T extends boolean = true> {
  sections?:
    | T
    | {
        title?: T;
        content?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "works-groups_select".
 */
export interface WorksGroupsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  items?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "works_select".
 */
export interface WorksSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  year?: T;
  poster?: T;
  tags?: T;
  description?: T;
  videoUrl?: T;
  category?: T;
  subcategory?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        keywords?: T;
      };
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members_select".
 */
export interface TeamMembersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  bio?: T;
  photo?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "press-items_select".
 */
export interface PressItemsSelect<T extends boolean = true> {
  title?: T;
  source?: T;
  date?: T;
  url?: T;
  description?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        poster?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-config".
 */
export interface SiteConfig {
  id: number;
  brand: {
    name: string;
    tagline?: string | null;
    logo?: (number | null) | Media;
    favicon?: (number | null) | Media;
  };
  colors?: {
    background?: string | null;
    foreground?: string | null;
    rfeRed?: string | null;
    rfeRose?: string | null;
    rfeGold?: string | null;
  };
  sectionTones?: {
    deep?: string | null;
    charcoal?: string | null;
    slate?: string | null;
    warm?: string | null;
    cool?: string | null;
    ember?: string | null;
    dusk?: string | null;
  };
  typography?: {
    brandFont?: string | null;
    sansFont?: string | null;
    serifFont?: string | null;
    radiusBase?: string | null;
  };
  easings?: {
    emerge?: string | null;
    quiet?: string | null;
    sharp?: string | null;
  };
  seo?: {
    titleTemplate?: string | null;
    defaultTitle?: string | null;
    defaultDescription?: string | null;
    keywords?: string | null;
    ogImage?: (number | null) | Media;
    siteUrl?: string | null;
  };
  contact?: {
    email?: string | null;
    phone?: string | null;
    address?: string | null;
  };
  social?: {
    instagram?: string | null;
    linkedin?: string | null;
    vimeo?: string | null;
    tiktok?: string | null;
    imdb?: string | null;
  };
  about?: {
    paragraphs?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    heroHeadline?: string | null;
    heroSubheadline?: string | null;
    heroParagraph?: string | null;
  };
  legal?: {
    title?: string | null;
    subtitle?: string | null;
    sections?:
      | {
          title: string;
          paragraphs?:
            | {
                text: string;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  header?: {
    items?:
      | {
          label: string;
          href: string;
          isExternal?: boolean | null;
          id?: string | null;
        }[]
      | null;
  };
  footer?: {
    legalLabel?: string | null;
    copyrightText?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-config_select".
 */
export interface SiteConfigSelect<T extends boolean = true> {
  brand?:
    | T
    | {
        name?: T;
        tagline?: T;
        logo?: T;
        favicon?: T;
      };
  colors?:
    | T
    | {
        background?: T;
        foreground?: T;
        rfeRed?: T;
        rfeRose?: T;
        rfeGold?: T;
      };
  sectionTones?:
    | T
    | {
        deep?: T;
        charcoal?: T;
        slate?: T;
        warm?: T;
        cool?: T;
        ember?: T;
        dusk?: T;
      };
  typography?:
    | T
    | {
        brandFont?: T;
        sansFont?: T;
        serifFont?: T;
        radiusBase?: T;
      };
  easings?:
    | T
    | {
        emerge?: T;
        quiet?: T;
        sharp?: T;
      };
  seo?:
    | T
    | {
        titleTemplate?: T;
        defaultTitle?: T;
        defaultDescription?: T;
        keywords?: T;
        ogImage?: T;
        siteUrl?: T;
      };
  contact?:
    | T
    | {
        email?: T;
        phone?: T;
        address?: T;
      };
  social?:
    | T
    | {
        instagram?: T;
        linkedin?: T;
        vimeo?: T;
        tiktok?: T;
        imdb?: T;
      };
  about?:
    | T
    | {
        paragraphs?:
          | T
          | {
              text?: T;
              id?: T;
            };
        heroHeadline?: T;
        heroSubheadline?: T;
        heroParagraph?: T;
      };
  legal?:
    | T
    | {
        title?: T;
        subtitle?: T;
        sections?:
          | T
          | {
              title?: T;
              paragraphs?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  header?:
    | T
    | {
        items?:
          | T
          | {
              label?: T;
              href?: T;
              isExternal?: T;
              id?: T;
            };
      };
  footer?:
    | T
    | {
        legalLabel?: T;
        copyrightText?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?: {
      relationTo: 'pages';
      value: number | Page;
    } | null;
    global?: string | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}